image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential libssl-dev pkg-config
  - rustup component add clippy

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose --locked
    - cargo fmt --all -- --check
    - cargo clippy
