[package]
name = "matrixserver"
version = "0.1.0"
authors = ["timokoesters <timo@koesters.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", features = ["tls"] }
http = "0.2.1"
ruma-client-api = { git = "https://github.com/ruma/ruma-client-api" }
pretty_env_logger = "0.4.0"
log = "0.4.8"
sled = "0.31.0"
directories = "2.0.2"
ruma-identifiers = "0.14.1"
ruma-api = "0.15.0-dev.1"
ruma-events = "0.17.0"
js_int = "0.1.3"
