[package]
name = "matrixserver"
version = "0.1.0"
authors = ["timokoesters <timo@koesters.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
http = "0.2.0"
ruma-client-api = "0.6.0"
pretty_env_logger = "0.4.0"
