# Conduit
version: '3'

services:
    conduit:
        image: conduit_homeserver
        restart: unless-stopped
        ports:
            - 14004:14004
        volumes:
            - db:/srv/conduit/.local/share/conduit
        environment:
            ROCKET_SERVER_NAME: example.com  # replace with your own name
            ### Uncomment and change values as needed
            # ROCKET_LOG: normal
            # ROCKET_PORT: 14004
            # ROCKET_REGISTRATION_DISABLED: 'true'
            # ROCKET_ENCRYPTION_DISABLED: 'true'
            # ROCKET_DATABASE_PATH: /srv/conduit/.local/share/conduit
            # ROCKET_WORKERS: 10
            # ROCKET_MAX_REQUEST_SIZE: 20_000_000  # in bytes, ~20 MB

volumes:
    db:
