# Conduit
version: '3'

services:
    conduit:
        image: conduit_homeserver
        restart: unless-stopped
        ports:
            - 14004:14004
        volumes:
            - db:/data/sled
        environment:
            ROCKET_SERVER_NAME: example.com  # replace with your own name
            ### Uncomment and change values as needed
            #ROCKET_LOG: normal
            #ROCKET_REGISTRATION_DISABLED: 'true'
            #ROCKET_DATABASE_PATH: /data/sled
            #ROCKET_WORKERS: 10

volumes:
    db:
