[global]
server_name = "your.server.name"
#registration_disabled = true

# Default path is in this user's data
#database_path = "/home/timo/MyConduitServer"

port = 14004
address = "0.0.0.0"

#[global.tls]
#certs = "/etc/letsencrypt/live/your.server.name/fullchain.pem"
#key = "/etc/letsencrypt/live/your.server.name/privkey.pem"
