# Conduit - Behind Traefik Reverse Proxy
version: '3'

services:
    homeserver:
        ### If you already built the Conduit image with 'docker build', then you can uncomment the
        ### 'image' line and comment out the 'build' option.
        # image: conduit_homeserver:latest
        ### If you want meaningful labels in you built Conduit image, you should run docker-compose like this:
        ### CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ') VERSION=$(grep -m1 -o '[0-9].[0-9].[0-9]' Cargo.toml) docker-compose up -d
        build:
            context: .
            args:
                CREATED:
                VERSION:
                LOCAL: false
                GIT_REF: HEAD
        restart: unless-stopped
        volumes:
            - db:/srv/conduit/.local/share/conduit
            ### Uncomment if you want to use Rocket.toml to configure Conduit
            ### Note: Set env vars will override Rocket.toml values
            # - ./Rocket.toml:/srv/conduit/Rocket.toml
        networks:
            - proxy
        environment:
            ROCKET_SERVER_NAME: localhost:8000  # replace with your own name
            ### Uncomment and change values as desired
            # ROCKET_LOG: normal  # Available levels are: off, debug, normal, critical
            # ROCKET_PORT: 8000
            # ROCKET_REGISTRATION_DISABLED: 'true'
            # ROCKET_ENCRYPTION_DISABLED: 'true'
            # ROCKET_DATABASE_PATH: /srv/conduit/.local/share/conduit
            # ROCKET_WORKERS: 10
            # ROCKET_MAX_REQUEST_SIZE: 20_000_000  # in bytes, ~20 MB

    ### Uncomment if you want to use your own Element-Web App.
    ### Note: You need to provide a config.json for Element and you also need a second
    ###       Domain or Subdomain for the communication between Element and Conduit
    ### Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/riot-web:latest
    #     restart: unless-stopped
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     networks:
    #         - proxy
    #     depends_on:
    #         - homeserver

volumes:
    db:

networks:
    # This is the network Traefik listens to, if you network has a different
    # name, don't forget to change it here and in the docker-compose.override.yml
    proxy:
        external: true
